site_name: Dell EMC PE WSMAN Tools
repo_url: https://github.com/rchaganti/DellPEWSManTools
theme: readthedocs
pages:
  - Home: index.md
  - BIOS:
    - Get-PEBIOSAttribute: PEBIOS/Get-PEBIOSAttribute.md
    - Set-PEBIOSAttribute: PEBIOS/Set-PEBIOSAttribute.md
    - Get-PEBootOrder: PEBIOS/Get-PEBootOrder.md
    - Get-PESystemOneTimeBootSetting: PEBIOS/Get-PESystemOneTimeBootSetting.md
    - Set-PESystemOneTimeBootSetting: PEBIOS/Set-PESystemOneTimeBootSetting.md
  - DRAC:
    - Find-PEDRAC: PEDRAC/Find-PEDRAC.md
    - Get-PEADGroupInfo: PEDRAC/Get-PEADGroupInfo.md
    - Get-PEDRACAttribute: PEDRAC/Get-PEDRACAttribute.md
    - Get-PEDRCInformation: PEDRAC/Get-PEDRACInformation.md
    - Get-PEDRACPrivilege: PEDRAC/Get-PEDRACPrivilege.md
    - Get-PEDRACUser: PEDRAC/Get-PEDRACUser.md
    - Import-PECertificate: PEDRAC/Import-PECertificate.md
    - New-PEDRACSession: PEDRAC/New-PEDRACSession.md
    - Reset-PEDRAC: PEDRAC/Reset-PEDRAC.md
    - Set-PEADRoleGroup: PEDRAC/Set-PEADRoleGroup.md
    - Set-PECommonADSetting: PEDRAC/Set-PECommonADSetting.md
    - Set-PEStandardSchemaSetting: PEDRAC/Set-PEStandardSchemaSetting.md